

minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"


locale                   : en_US
title                    : "Data Visualization" 
title_separator          : "-"
description              : "Learn the science behind learning tools"
title_separator          : "-"
teaser                   : "/assets/images/Teaser.jpg"
description              : "California State University Fullerton Students"
url                      : https://Thedatavizclub.github.io
repository               : Thedatavizclub/Thedatavizclub.github.io
breadcrumbs              : true # true, false (default)
words_per_minute         : 150
github                   : [metadata]
show_calendar            : true

analytics:
  provider               : "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :  "UA-109687303-1"


minima.date_format       : "%b %-d, %Y"

social:
  type                   : Organization 
  name                   : Data Visualization @CSU Fullerton
  links: 


author:
  name             : "Data Visualization Club @CSU Fullerton"
  avatar           : "/assets/images/DVCLogo/DVC_Logo.jpg"
  bio              : ""
  location         : "Fullerton, California"
  email            : dvc@fullerton.edu
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : 
  foursquare       :  
  github           : Thedatavizclub
  google_plus      : 
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : 
  pinterest        :
  soundcloud       :
  stackoverflow    : 
  steam            :
  tumblr           :
  twitter          : 
  vine             :
  weibo            :
  xing             :
  youtube          : # "https://youtube.com/c/MichaelRoseDesign"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

include:
  - .htaccess
  - _pages
exclude:
  - _site
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: America/Los_Angeles


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      comments: false
      sidebar:
        nav: "docs"
  # _foo
  - scope:
      path: ""
      type: foo
    values:
      layout: single
      author_profile: true
      comments: false
    # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

